### ISSUE TITLE
cannot 'data-lad publish ...' to 'afni_ci_test_data'

### ISSUE THREAD

**Issue by mrneont** [afni/afni_ci_test_data#2]
@leej3 

I have successfully gone through all the steps on the instruction page *except* the last command:
`datalad publish --transfer-data=all --to=afni_ci_test_data`

I have done this on three separate systems:  Ubuntu 20.04, Mac 10.15 and lastly Ubuntu 16.04.  Note that on this last one, I am on the 'safni' machine.

Strictly following the instructions, when I try the above command, I get this error:
```
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --to=afni_ci_test_data --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3 -- .' failed with exitcode 1 under /home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data
git-annex: copy: 6 failed
```

The same occurs even if I edit my .git/config file with the extra information[, suggested on the main instruction page.](https://github.com/afni/afni_ci_test_data#git-configuration)

One problem is:  the instructions say users must have git-annex ver=7.  However, the environment.yml only installs datalad, which takes care of installing git-annex, and I cannot specify git-annex version anywhere.  And datalad seems to always install git-annex ver=8.  

On a Mac, I could not get homebrew to install git-annex ver=7 either through building or going through the git repo.  On the current safni Ubuntu, I tried editing my conda environment by uninstalling git-annex ver=8, then installing git-annex ver=7 (and then I had to reinstall datalad, too), with:
```
conda remove git-annex
conda config --append channels conda-forge
conda install git-annex=7
conda install datalad
```
However, when running the datalad publish command again, I now got this error:
```
CommandError: 'git -c diff.ignoreSubmodules=none annex wanted afni_ci_test_data -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data
git-annex: Repository version 8 is not supported. Upgrade git-annex.
```
So, I seem to be stuck between datalad requirement of git-annex ver=8 and the afni_tests_ci_data requirement of git-annex ver=7.  (Assuming that *is* the origin of the original failure message;  I don't even know.)

Any advice is welcome, thanks.

**Comment by leej3** [comment]
> the instructions say users must have git-annex ver=7

Previously I enforced this by changing the repo configuration during tests execution. I'm not sure whether previous versions of the git-annex v8 tool supported v7 repos but git-annex v8 certainly does not now. Hopefully [my fix](https://github.com/afni/afni/commit/76b8a4f64e89b0f3cdb08b2c10cebb5ae07202f1) will work... only support v8 repos... using git-annex v8.

> And datalad seems to always install git-annex ver=8

I'm not sure this is entirely correct. My understanding is that conda does not install git-annex as a dependency on MacOS (it is not currently built for this OS on condo-forge). On Linux I imagine this is very frequently true though. 

> So, I seem to be stuck between datalad requirement of git-annex ver=8 and the afni_tests_ci_data requirement of git-annex ver=7

As mentioned above, v8 git-annex installations should now have no problems after the fix applied in https://github.com/afni/afni/commits/make_some_ci_fixes is merged. Have a try again with that.

**Comment by mrneont** [comment]
Hi, @leej3 ---

Your mentioned commits above were merged into the AFNI repo yesterday, and I tried this again today, from safni.

I made a branch of the afni repo ("update_test_ci") to undo these changes to ptaylor_tests from these commits:
```
47888ee190eee19a4f62ec33539716ea4dbbca92
a3e358103758bd5e35c461dd4ae8fb775ff8bc02
```
.... so that the diffs in 3dClusterize behavior would be recognized. 

I follow the instructions again, resulting in the same error in the 2nd "datalad publish .." command:
```
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
Total (0 ok, 6 failed out of 6):   0%|                                               | 0.00/123k [00:18<?, ?B/s][WARNING] Running copy resulted in stderr output: git-annex: copy: 6 failed
```

Below is the gory detail of what I did (including some output in case it helps).

One question that came up in discussion:  rodgersleejg is the owner of the afni_ci_test_data directory on 'afni'.  Now, the permissions are "drwxrwsr-x", so either afniHQ (the person logged in to safni) or mrneont (the person committing the github changes) should have write permissions there because they are in the same group, right?  Or is that potentially an issue?

Thanks,
pt

------------------------------------------
NB: this is being run on safni, as afniHQ

We are mostly following instructions here: 
    https://github.com/afni/afni_ci_test_data
 
We make a new afni branch, because we wanted the testing of 3dClusterize *on* and to see the differences it produces from the current 'test bed' answer.

The afni_dev conda env already exists (because of afni_doc building).


Get AFNI binaries:
```
cd 
cd ~/FOR_TEST_AFNI
git clone https://github.com/afni/afni.git
```


Make a new branch: will want to have full testing here in ptaylor tests
```
cd afni
git checkout -b update_test_ci
```


Turn back on testing of 3dClusterize, I think
```
cd tests/scripts
emacs test_ptaylor.py
```
# [editing in a couple places, undoing a couple recent commits in master branch]
```
git commit -am "test_ptaylor.py: turn back on diffing for newly running prog, 3dClusterize"
git push origin update_test_ci
cd ../..
```


Now start doing the datalad stuff
```
cd tests
conda activate afni_dev
```

Get repo
`datalad install https://github.com/afni/afni_ci_test_data.git`
... which outputs:
```
[INFO   ] Scanning for unlocked files (this may take some time)                                                 
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                           
[INFO   ] access to 2 dataset siblings afnitestdata, cloud not auto-enabled, enable with:
| 		datalad siblings -d "/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data" enable -s SIBLING 
install(ok): /home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data (dataset)
```

Run the ptaylor tests the first time; 'abin' location from `which afni`
```
./run_afni_tests.py                            \
    --abin=~/afni.build/pub.dist/bin/linux_ubuntu_16_64 \
    --file scripts/test_ptaylor.py             \
    local
```
... which outputs:
```
Running tests... if you have not run them before the first time will take a while because the test data has to be downloaded
Executing: /home/afniHQ/miniconda3/envs/afni_dev/bin/python3 -m pytest /home/afniHQ/FOR_TEST_AFNI/afni/tests/scripts/test_ptaylor.py --tb=no -r fEs --show-capture=no


 The output is being written to: /home/afniHQ/FOR_TEST_AFNI/afni/tests/output_of_tests/output_2021_06_15_151132
============================================= test session starts ==============================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/afniHQ/FOR_TEST_AFNI/afni/tests, configfile: pytest.ini
plugins: xdist-2.2.0, forked-1.2.0, cov-2.10.1
collected 24 items                                                                                             

scripts/test_ptaylor.py ...s.s...sssss...FFs....                                                         [100%]

Test output is written to:  /home/afniHQ/FOR_TEST_AFNI/afni/tests/output_of_tests/output_2021_06_15_151132


=========================================== short test summary info ============================================
FAILED scripts/test_ptaylor.py::test_3dClusterize - FileNotFoundError
FAILED scripts/test_ptaylor.py::test_3dClusterize_new - FileNotFoundError
SKIPPED [1] scripts/test_ptaylor.py:87: need --runveryslow option to run
SKIPPED [1] scripts/test_ptaylor.py:138: need --runslow option to run
SKIPPED [1] scripts/test_ptaylor.py:216: need --runveryslow option to run
SKIPPED [1] scripts/test_ptaylor.py:245: need --runslow option to run
SKIPPED [1] scripts/test_ptaylor.py:269: need --runveryslow option to run
SKIPPED [1] scripts/test_ptaylor.py:307: need --runslow option to run
SKIPPED [1] scripts/test_ptaylor.py:330: need --runslow option to run
SKIPPED [1] scripts/test_ptaylor.py:453: need --runslow option to run
============================= 2 failed, 14 passed, 8 skipped in 221.26s (0:03:41) ==============================
```

Rerun tests so accept output:
```
./run_afni_tests.py                     \
     --abin=~/afni.build/pub.dist/bin/linux_ubuntu_16_64 \
     --file scripts/test_ptaylor.py     \
     -e="--create-sample-output"        \
     --lf                               \
     -v verbose                         \
     local
```
... which outputs:
```
Running tests... if you have not run them before the first time will take a while because the test data has to be downloaded
Executing: /home/afniHQ/miniconda3/envs/afni_dev/bin/python3 -m pytest /home/afniHQ/FOR_TEST_AFNI/afni/tests/scripts/test_ptaylor.py --tb=no -r fEsxX -v --log-cli-level=INFO -s --lf --create-sample-output


 The output is being written to: /home/afniHQ/FOR_TEST_AFNI/afni/tests/output_of_tests/output_2021_06_15_152036
============================================= test session starts ==============================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/afniHQ/miniconda3/envs/afni_dev/bin/python3
cachedir: .pytest_cache
rootdir: /home/afniHQ/FOR_TEST_AFNI/afni/tests, configfile: pytest.ini
plugins: xdist-2.2.0, forked-1.2.0, cov-2.10.1
collected 24 items / 22 deselected / 2 selected                                                                
run-last-failure: rerun previous 2 failures

scripts/test_ptaylor.py::test_3dClusterize 
------------------------------------------------ live log call -------------------------------------------------
INFO     test_3dClusterize:tools.py:463 cd /home/afniHQ/FOR_TEST_AFNI/afni/tests;3dClusterize -echo_edu -mask ./afni_ci_test_data/AFNI_demos/FATCAT_DEMO/mask_DWI+orig.BRIK.gz -inset ./afni_ci_test_data/AFNI_demos/FATCAT_DEMO/SOME_ICA_NETS_in_DWI+orig.BRIK.gz -ithr 0 -idat 0 -bisided -3 3 -NN 2 -clust_nvox 200 -pref_map output_of_tests/output_2021_06_15_152036/ptaylor/test_3dClusterize/o.3dClusterize_MAP.nii.gz -pref_dat output_of_tests/output_2021_06_15_152036/ptaylor/test_3dClusterize/o.3dClusterize_DAT.nii.gz
PASSED
scripts/test_ptaylor.py::test_3dClusterize_new 
------------------------------------------------ live log call -------------------------------------------------
INFO     test_3dClusterize_new:tools.py:463 cd /home/afniHQ/FOR_TEST_AFNI/afni/tests;3dClusterize -echo_edu -mask ./afni_ci_test_data/AFNI_demos/FATCAT_DEMO/mask_DWI+orig.BRIK.gz -inset ./afni_ci_test_data/AFNI_demos/FATCAT_DEMO/SOME_ICA_NETS_in_DWI+orig.BRIK.gz -ithr 0 -idat 0 -bisided -3 3 -NN 2 -clust_nvox 200 -pref_map output_of_tests/output_2021_06_15_152036/ptaylor/test_3dClusterize_new/o.3dClusterize_MAP.nii.gz -pref_dat output_of_tests/output_2021_06_15_152036/ptaylor/test_3dClusterize_new/o.3dClusterize_DAT.nii.gz
PASSED

Test output is written to:  /home/afniHQ/FOR_TEST_AFNI/afni/tests/output_of_tests/output_2021_06_15_152036

 Sample output is written to: /home/afniHQ/FOR_TEST_AFNI/afni/tests/sample_output_of_tests/sample_output_2021_06_15_152036


======================================= 2 passed, 22 deselected in 0.77s =======================================
```

Copy data:
```
rsync -aP                                                               \
    sample_output_of_tests/sample_output_2021_06_15_152036/             \
    afni_ci_test_data/sample_test_output/
```
... which outputs:
```
sending incremental file list
./
ptaylor/
ptaylor/test_3dClusterize/
ptaylor/test_3dClusterize/o.3dClusterize_DAT.nii.gz
         46,886 100%   13.46MB/s    0:00:00 (xfr#1, to-chk=11/16)
ptaylor/test_3dClusterize/o.3dClusterize_MAP.nii.gz
          7,591 100%    7.24MB/s    0:00:00 (xfr#2, to-chk=10/16)
ptaylor/test_3dClusterize/captured_output/
ptaylor/test_3dClusterize/captured_output/test_3dClusterize_cmd.log
          6,823 100%    6.51MB/s    0:00:00 (xfr#3, to-chk=8/16)
ptaylor/test_3dClusterize/captured_output/test_3dClusterize_stderr.log
            761 100%  743.16kB/s    0:00:00 (xfr#4, to-chk=7/16)
ptaylor/test_3dClusterize/captured_output/test_3dClusterize_stdout.log
          2,606 100%    2.49MB/s    0:00:00 (xfr#5, to-chk=6/16)
ptaylor/test_3dClusterize_new/
ptaylor/test_3dClusterize_new/o.3dClusterize_DAT.nii.gz
         46,888 100%   44.72MB/s    0:00:00 (xfr#6, to-chk=5/16)
ptaylor/test_3dClusterize_new/o.3dClusterize_MAP.nii.gz
          7,591 100%    7.24MB/s    0:00:00 (xfr#7, to-chk=4/16)
ptaylor/test_3dClusterize_new/captured_output/
ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_cmd.log
          6,855 100%    6.54MB/s    0:00:00 (xfr#8, to-chk=2/16)
ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_stderr.log
            769 100%  750.98kB/s    0:00:00 (xfr#9, to-chk=1/16)
ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_stdout.log
          2,614 100%    2.49MB/s    0:00:00 (xfr#10, to-chk=0/16)
```

Add/commit to datalad repo
```
cd afni_ci_test_data
datalad save -m 'update sample data: ptaylor test, 3dClusterize'
```
... which outputs:
```
add(ok): sample_test_output/ptaylor/test_3dClusterize/captured_output/test_3dClusterize_cmd.log (file)          
add(ok): sample_test_output/ptaylor/test_3dClusterize/captured_output/test_3dClusterize_stderr.log (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize/captured_output/test_3dClusterize_stdout.log (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize/o.3dClusterize_DAT.nii.gz (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize/o.3dClusterize_MAP.nii.gz (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_cmd.log (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_stderr.log (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize_new/captured_output/test_3dClusterize_new_stdout.log (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize_new/o.3dClusterize_DAT.nii.gz (file)
add(ok): sample_test_output/ptaylor/test_3dClusterize_new/o.3dClusterize_MAP.nii.gz (file)
save(ok): . (dataset)
action summary:
  add (ok: 10)
  save (ok: 1)
```

Publish to github:
`datalad publish --transfer-data=all --to=origin`
... which outputs:
```
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) to origin 
Username for 'https://github.com': mrneont
Password for 'https://mrneont@github.com': 
publish(ok): . (dataset) [pushed to origin: ['dd26b25bc..563a538c5', 'b8532214e..6bca54203']]   
```

Publish to afni server:
`datalad publish --transfer-data=all --to=afni_ci_test_data`

... which produces output that makes me sad:
```
datalad publish --transfer-data=all --to=afni_ci_test_data
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
Total (0 ok, 6 failed out of 6):   0%|                                               | 0.00/123k [00:18<?, ?B/s][WARNING] Running copy resulted in stderr output: git-annex: copy: 6 failed
```

**Comment by leej3** [comment]
Chown to your username. No point it  being owned by me. 

The 6 missing files might 6 files created earlier in the history when you were on another host but couldn’t upload to the afni server. 

I’m not sure the easiest way to datalad that it’s ok that it’s missing those files. I’d take a look through the datalad handbook or raise an issue on GitHub (the datalad repo). 

It’s hard to debug without access myself. 

I can take a closer look at the saga outlined above on the weekend.

**Comment by mrneont** [comment]
Hi, @leej3 -

OK, thanks.  The number of commands aren't long, I just included most of the text output in case there were some hint of what was going wrong there.

I tried to put some kind of verbosity option on the "datalad publish ..." command, but `-l 9` just produced an error. 

I also note that in the datalad help docs on "datalad publish ...", they state:
`This command is deprecated. It will be removed from DataLad eventually, but no earlier than the 0.15 release. The PUSH command (new in 0.13.0) provides an alternative interface. Critical differences are that PUSH transfers annexed data by default and does not handle sibling creation (i.e. it does not have a –MISSING option).`
http://docs.datalad.org/en/stable/generated/man/datalad-publish.html

The current datalad version being used in the afni_ci_tests_data framework is:  datalad 0.13.6.
From their main doc page, the current available datalad version is 0.14.4;  as of 0.14.0, 'datalad push' became deprecated, and it will be removed at 0.15.0.

**Comment by mrneont** [comment]
I have now also opened a thread on NeuroStars, which is the datalad question board:
https://neurostars.org/t/datalad-publish-fails/19539/2

**Comment by mrneont** [comment]
@leej3 -

OK, we are revisiting being able to update the afni_ci_tests_data. 

Some progress has been made:  we changed the permissions of the directory on 'afni' to be owned by afniHQ, who is doing the work at the moment.  The tests are being run from 'safni', to be able to (hopefully) push to 'afni' easily.

Also, I have edited the .git/config/ file in the repo where the testing is being run, setting "pushurl = ...", following this tip:
https://github.com/afni/afni_ci_test_data#git-configuration

After doing all that, we now get further with the final attempt to publish to the afni server, *but* there is a new error:

```
safni:~/FOR_TEST_AFNI/afni/tests/afni_ci_test_data> datalad publish --transfer-data=all --to=afni_ci_test_data
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
[WARNING] Running copy resulted in stderr output: git-annex-shell: Command not found.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
rsync exited 12
git-annex-shell: Command not found.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
rsync exited 12
git-annex-shell: Command not found.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
rsync exited 12
git-annex: copy: 1 failed
```

Does the "afniHQ" user need something setup with git-annex-shell on the 'afni' server?  Or is this something to manage from the 'safni' (=test-running) side?

I wasn't sure if this tip:
https://github.com/afni/afni_ci_test_data#annex-remote-accessibility
... referred to this situation, but I still got the same git-annex-shell error even after running:
`git-annex enableremote afni_ci_test_data`

Any suggestions would be appreciated.

thanks,
pt

**Comment by mrneont** [comment]
Perhaps, do you have a *.yml for how you set up your own environment on 'afni'?  I guess that "git-annex-shell" must be required, but are there other pieces, too?

--pt

**Comment by leej3** [comment]
It's been almost 3 years since I set it up so the details are a little hazy at this point. The bits that I struggled with were all server side traffic blocking. They are hopefully all remedied at this point, and indeed not swapped out for new ones. You're description sounds correct. The server needs git-annex shell available at the very least for the upload to work (a stripped down program used for the git repository communications to drop the attack service). I didn't have admin access so this would have been done via conda. Using conda again for making this available is the sensible choice anyway because you'll likely get a more up to date version of the git-annex shell . 

 One detail that is a little tricky is determining the shell type of the communication. Typically one adds shell setup to .bashrc, and in this case the conda environment needs to be added to make sure it is available (something like `export PATH="/path/to/conda/env/bin:$PATH"`) but in this case I imagine it is a non-interactive login shell so determining the correct startup file to choose will take some thought/experimentation.

This is a fairly standard setup for datalad so I would expect there to be some documentation. I find the git annex docs hard to work through but they may help if the datalad docs have not provided enough information. Also, if it still exists, you can switch to my user  on the afni server for details (`sudo su <username>`).

**Comment by mrneont** [comment]
OK.  It seems like the issue now is to have afniHQ's account on 'afni' mirror how your account on 'afni' was setup.  I did try adding your account's ~/miniconda3/bin/ to afniHQ's path---but indeed, afniHQ's default shell is tcsh, so it sounds like maybe that will have to be changed to bash;  that is good to know, thanks.

**Comment by mrneont** [comment]
I have made 'bash' the default shell for user 'afniHQ' on 'afni'.  And I have installed datalad on that account via conda, following datalad instructions (this includes git-annex and git-shell-annex).

The current error when running is this:
```
$ datalad publish --transfer-data=all --to=afni_ci_test_data
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) to afni_ci_test_data 
CommandError: 'git push --progress --porcelain afni_ci_test_data master git-annex' failed with exitcode 128 under /home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data
export: Command not found.
fatal: bad config value for 'receive.denycurrentbranch' in config
CommandError: 'ssh -o ControlPath=/home/afniHQ/.cache/datalad/sockets/cb28eeff afni.nimh.nih.gov 'export "PATH=/home/rodgersleejg/miniconda3/bin:$PATH"; git-receive-pack '"'"'/fraid/pub/dist/data/afni_ci_test_data'"'"''' failed with exitcode 128
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I see that /home/rodgersleejg/.cache/datalad/sockets exists (though I can't see anything listed there if I try "sudo ls ..."), but /home/rodgersleejg/.cache/datalad does not.  It also seems like the PATH export is hardwired to your old account with the "/home/rodgersleejg/miniconda3/bin:$PATH" part.

It seems like there might be some things that the rodgersleejg account has set up which are not available for afniHQ, and there is a hierarchy of files sourced, such as:
```
.bash_aliases           .bash_history           .bash_profile           .bashrc                 
.bash_eternal_history   .bash_logout            .bash_prompt            .bashrc-miniconda3.bak  
.extras .functions 
```

Even if I try adding the following to afniHQ's ~/.bashrc, I still get the same error as above:
```
export PATH=$PATH:~rodgersleejg/miniconda3/bin

for file in ~rodgersleejg/.{path,exports,extra,extras}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
```

--pt

**Comment by mrneont** [comment]
I think there is further progress---

On the server machine 'afni', the default shell is now bash, and datalad is installed.  I am not trying to use anything from the ~rodgersleejg/ user paths.  The git configuration username/email is set for the afniHQ user.  The afni_ci_test_data directory there is entirely owned by afniHQ.

So now, on the 2nd publish step, I now get some "ok" messages (!!!), but then some errors:

```
$ datalad publish --transfer-data=all --to=afni_ci_test_data
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) data to afni_ci_test_data 
afniHQ@afni.nimh.nih.gov's password:                                                                 | 0.00/16.7M [00:00<?, ?B/s]
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_DW/stat.nii.gz (file)                                                 
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_MAD/stat.nii.gz (file)                                                
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_MASDx/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_MSSD/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_MSSDsqrt/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_absmax/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_abssum/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_argabsmax/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_argabsmax1/stat.nii.gz (file)
publish(ok): sample_test_output/3dTstat/test_3dTstat_basic_argmax/stat.nii.gz (file)
[INFO   ] Publishing Dataset(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data) to afni_ci_test_data 
[ERROR  ] failed to push to afni_ci_test_data: refs/heads/git-annex -> refs/heads/git-annex [rejected] (fetch first); refs/heads/master -> refs/heads/master [remote rejected] (push-to-checkout hook declined); [publish(/home/afniHQ/FOR_TEST_AFNI/afni/tests/afni_ci_test_data)] 
  [29 similar messages have been suppressed]
publish(error): . (dataset) [failed to push to afni_ci_test_data: refs/heads/git-annex -> refs/heads/git-annex [rejected] (fetch first); refs/heads/master -> refs/heads/master [remote rejected] (push-to-checkout hook declined);]
action summary:
  publish (error: 1, ok: 39)
```

Does this strike you as something obvious to troubleshoot?

--pt

**Comment by leej3** [comment]
Not obvious no. I'm not sure what's wrong. Looks like you're very close though!

+ I think the remote either needs to be a bare repository (no files present other than the .git directory) or have the correct setting of the denyCurrentBranch in the git repository. See [here](https://stackoverflow.com/questions/12265729/what-are-the-consequences-of-using-receive-denycurrentbranch-in-git). Based on the error message it seems like it is trying to checkout the file on the remote and failing because of a pre-existing one or something like that.


Some thoughts (likely unrelated):




+ Sometimes the files that should be pushed are missing locally and you need to figure out where they are stored and push from there (or delete the files, commit the deletion and push that history instead to make sure people don't get errors in trying to download that file).

+ Sometime an odd permissions error occurs that you need to make sure perms are fixed in the repo described [here](https://github.com/datalad/datalad/issues/5176). If not now you will need it at some point:
```
find /fraid/pub/dist/data/afni_ci_test_data -type d  ! -perm -o=x -exec chmod o+x {} \;; find /fraid/pub/dist/data/afni_ci_test_data -type f  ! -perm -o=r -exec chmod o+r {} \;
```

**Comment by mrneont** [comment]
The amazing @yarikoptic has resolved these final issues.  

The main problem appeared to be having extraneous *.html files in this /fraid/pub/dist/data/afni_ci_test_data/ directory.  Some were being tracked in the git repo (leading to "uncommitted changes" hanging out there), and some were untracked changes. These have been purged.

Yarik also made a couple tweaks:
https://github.com/afni/afni/commit/61cd27da71724228aab8ef85f7f6d6f67ba5f0fd
https://github.com/afni/afni/commit/6e3d37280bffcd74a2cae17debe2d6f46d4770f8

At his behest, we added an `exit 0` after `git update-server-info` in .git/hooks/post-update on the "afni" machine, to speed up the transfer process (all content file UUIDs aren't analyzed for datalad browser interaction, which we don't need).

... and he noted that we should `datalad push` instead of the pair of `datalad publish ..` commands in the notes (for which I will make a PR), because the "publish" is being deprecated, and the single push will accomplish both interactions now (part of his settings tweaks, above, I believe).

So, the testing framework is running successfully again, just in time for the holidays...

**Comment by leej3** [comment]
Fantastic news. Thanks @yarikoptic
